image: alpine/edge
packages:
  - shellcheck
  - editorconfig-checker
  - shellspec
sources:
  - https://git.sr.ht/~mil/sxmo-utils
tasks:
  - shellcheck: |
      cd sxmo-utils
      find . -type f -name '*.sh' -print0 | xargs -0 shellcheck -x --shell=sh
  - shellspec: |
      cd sxmo-utils
      shellspec
  - editorconfig-check: |
      cd sxmo-utils
      ec
